name: mrfifo
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python>=3.8
    - samtools>=1.13
    - pip>=21.1
    - pysam>=0.16.0.1
    - pip:
        - pytest
        - pytest-cov
        - more-itertools>=8.7.0
        - setproctitle
        - isal
